## Array Creation

There are six types array creation in Numpy

### 1. Conversion from other python structure

In [2]:
#1d Array
arr = [1,2,3,4,5,6]
print(type(arr))

<class 'list'>


In [4]:
import numpy as np
arr1D = np.array(arr)
print(arr1D,type(arr1D))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [6]:
arr2D = np.array([[1,2],[3,4]])
arr2D

array([[1, 2],
       [3, 4]])

### 2. Intrinsic Numpy creation

In [8]:
## 1D creation
print(np.arange(10,dtype=int))
print(np.arange(10,dtype=float))
print(np.arange(2,3,0.1))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [9]:
# LinSpace
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
## 2D Creation

In [11]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(np.ones((3, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


### 3. Replicating, joining or mutating

In [21]:
a = np.array([1,2,3,4,5,6])
b = a[:2]
b+=1
print(b)
print(a)

[2 3]
[2 3 3 4 5 6]


In [22]:
a = np.array([1,2,3,4,5,6])
b = a[:2].copy()
b+=1
print(b)
print(a)

[2 3]
[1 2 3 4 5 6]


### 4. Reading from Disks and Space