## Basics Numpy

### Install Numpy
conda install numpy
or
pip install numpy

In [1]:
## Import numpy 
import numpy as np

#### Arrays

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [4]:
a,a.shape

(array([1, 2, 3, 4, 5, 6]), (6,))

In [5]:
# Zeroes
print(np.zeros(3))

[0. 0. 0.]


In [9]:
#ONes
print(np.ones(3))

[1. 1. 1.]


In [11]:
# Empty Array
print(np.empty(2))  ## Result will differs Everytime

[-5.73021895e-300  4.68093388e-310]


In [12]:
# create an array with a range of elements:

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [14]:
## Evenly Specified Intervals

print(np.arange(2,19,2))

##np.arange(startValue,EndValue,ValuetoInCrease)

[ 2  4  6  8 10 12 14 16 18]


In [16]:
# Linear  In a specified Interval
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
## Specifiy Data Type
x = np.ones(4,dtype = np.int64)
print(x)

[1 1 1 1]


## Adding, Sorting, Removing in Numpy Array

In [19]:
arr = np.array([2,1,3,9,5,6,8,1,4,5])

In [21]:
##  Sorting
print(np.sort(arr))

[1 1 2 3 4 5 5 6 8 9]


In [22]:
#In addition to sort, which returns a sorted copy of an array, you can use:

#argsort, which is an indirect sort along a specified axis,

#lexsort, which is an indirect stable sort on multiple keys,

#searchsorted, which will find elements in a sorted array, and

#partition, which is a partial sort.

In [23]:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [26]:
## Concatenate
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and size of an Array

In [27]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [29]:
# ndarray.ndim will tell you the number of axes, or dimensions, of the array.
print(array_example.ndim)

3


In [30]:
#ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape
print(array_example.size)

24


In [31]:
# Shaoe of the Array
print(array_example.shape)

(3, 2, 4)


### Reshape of an Array

In [32]:
a = np.arange(9)

In [36]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
## Reshape
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
np.reshape(a, newshape=(3, 3), order='C')
#C means to read/write the elements using C-like index order,

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.reshape(a, newshape=(3, 3), order='F')
# F means to read/write the elements using Fortran-like index order,

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [40]:
np.reshape(a, newshape=(3, 3), order='A')
#A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
#INdexing and Slicing
data = np.arange(10)

In [43]:
data[0:5]


array([0, 1, 2, 3, 4])

In [44]:
data[1:3]

array([1, 2])

In [45]:
data[-2:]

array([8, 9])

In [46]:

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [47]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a[ a < 5]

array([1, 2, 3, 4])

In [49]:
# Vstack -  Vertical Stack
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [50]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [51]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
#Hstack
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
x = np.arange(1, 25).reshape(2, 12)


In [55]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [56]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [57]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

### Basic Array operations

In [59]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)

In [62]:
data, ones

(array([1, 2]), array([1, 1]))

In [63]:
#Addition
data + ones

array([2, 3])

In [64]:
#Subtration
data -ones

array([0, 1])

In [65]:
#Multiplication
data * ones

array([1, 2])

In [66]:
#Division
data / ones

array([1., 2.])

In [70]:
## Sum
data =  np.arange(11)

In [71]:
data


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
np.sum(data)

55

In [74]:
##Row wise Sum
data =  np.arange(12).reshape(3,4)

In [75]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
data.sum(axis=0)

array([12, 15, 18, 21])

In [78]:
#Column wise sum
data.sum(axis=1)

array([ 6, 22, 38])

#### Broadcasting

In [80]:
data = np.array([1.6,3.1])
print(data * 2.0)

[3.2 6.2]


In [84]:
#Max
print(data.max())
# Min
print(data.min())
# Sum
print(data.sum())

3.1
1.6
4.7


### Matrices

In [85]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [86]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
print(data[0, 1]) # Oth Row 1st Column
print(data[1:3]) # First Row to 3 Row
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [92]:
#Unique
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [93]:
## Transponse

In [94]:
arr = np.arange(6).reshape((2, 3))

In [95]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [98]:
#Try arr.T also Works for transpose
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [99]:
## Reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [101]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [102]:
print(np.flip(arr2d))

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [104]:
#Reshaping Multi-dimensional
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [105]:
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [106]:
print(x.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [107]:
#Save and Load Numpy Objects

In [108]:
a = np.array([1, 2, 3, 4, 5, 6])

In [109]:
np.save("numpytest",a)

In [110]:
b = np.load('numpytest.npy')

In [111]:
b

array([1, 2, 3, 4, 5, 6])